### To check which gpu we are using if any available


In [41]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


# 00. Pytorch Fundamentals


In [42]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1


## Introduction to Tensors

### Creating tensors


In [43]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [44]:
# scalar dimention
scalar.ndim

0

In [45]:
# get tensor back as python int
scalar.item()

7

In [46]:
scalar.shape

torch.Size([])

In [47]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [48]:
# vector dimention
vector.ndim

1

In [49]:
vector.shape

torch.Size([2])

In [50]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [51]:
# MATRIX dimension
MATRIX.ndim

2

In [52]:
MATRIX[1]

tensor([ 9, 10])

In [53]:
MATRIX.shape

torch.Size([2, 2])

In [54]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [55]:
# TENSOR dimension
TENSOR.ndim

3

In [56]:
TENSOR.shape

torch.Size([1, 3, 3])

In [57]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [58]:
# Create random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9138, 0.1291, 0.6565, 0.4483],
        [0.3771, 0.4266, 0.6507, 0.4943],
        [0.2335, 0.9167, 0.8487, 0.3944]])

In [59]:
# shape of the random tensor
random_tensor.ndim

2

In [60]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 244, 244))  # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zero and Ones


In [61]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [62]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
# create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [64]:
ones.dtype

torch.float32

In [65]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [66]:
# use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [68]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [70]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float16, etc)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [71]:
float_32_tensor.dtype

torch.float32

In [75]:
# convert 32 bit tensor to the float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)