### To check which gpu we are using if any available


In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


# 00. Pytorch Fundamentals


In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1


In [3]:
mps_device = torch.device("mps")
mps_device

device(type='mps')

## Introduction to Tensors

### Creating tensors


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# scalar dimention
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

7

In [7]:
scalar.shape

torch.Size([])

In [8]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
# vector dimention
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
# MATRIX dimension
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
# TENSOR dimension
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [19]:
# Create random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5598, 0.2233, 0.4717, 0.5932],
        [0.2050, 0.7026, 0.9808, 0.1753],
        [0.7402, 0.4270, 0.3308, 0.3142]])

In [20]:
# shape of the random tensor
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 244, 244))  # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zero and Ones


In [22]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [27]:
# use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [31]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float16, etc)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
# convert 32 bit tensor to the float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
# this is one of the pytorch caveats, 
# we might thing this will through an error but instead it works fine and will return the multiplication of float32 type
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information fromn tensors (tensor attributes)

1. Tensors not right datatype -  to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape` or `tensor.size()`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [37]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4547, 0.1907, 0.2613, 0.9446],
        [0.2573, 0.2976, 0.2978, 0.1600],
        [0.9621, 0.1100, 0.7706, 0.5139]])

In [38]:
# find out details about some tensor
print(f"Some tensor: {some_tensor}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Some tensor: tensor([[0.4547, 0.1907, 0.2613, 0.9446],
        [0.2573, 0.2976, 0.2978, 0.1600],
        [0.9621, 0.1100, 0.7706, 0.5139]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Mulitplication (element-wise)
* Divison
* Matrix multiplication

In [39]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [43]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural neworks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [46]:
# element wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [47]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [48]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [61]:
%%timeit
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

7.57 µs ± 35.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [62]:
%%timeit
value = torch.matmul(tensor, tensor)

676 ns ± 1.98 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [63]:
### One of the most common errors in deep learning: shape errors
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [70]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.4380, 0.7431],
        [0.6528, 0.9800]])

In [68]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [69]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3)).shape

torch.Size([3, 3])