### To check which gpu we are using if any available


In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


# 00. Pytorch Fundamentals


In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1


In [3]:
mps_device = torch.device("mps")
mps_device

device(type='mps')

## Introduction to Tensors

### Creating tensors


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# scalar dimention
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

7

In [7]:
scalar.shape

torch.Size([])

In [8]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
# vector dimention
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
# MATRIX dimension
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
# TENSOR dimension
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [19]:
# Create random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7023, 0.3837, 0.1394, 0.6884],
        [0.0753, 0.2577, 0.0748, 0.1865],
        [0.9983, 0.6202, 0.7391, 0.3189]])

In [20]:
# shape of the random tensor
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 244, 244))  # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zero and Ones


In [22]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [27]:
# use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [31]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float16, etc)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
# convert 32 bit tensor to the float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
# this is one of the pytorch caveats, 
# we might thing this will through an error but instead it works fine and will return the multiplication of float32 type
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information fromn tensors (tensor attributes)

1. Tensors not right datatype -  to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape` or `tensor.size()`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [37]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0630, 0.7411, 0.7126, 0.6422],
        [0.7618, 0.5242, 0.3894, 0.4468],
        [0.8812, 0.2579, 0.1792, 0.4272]])

In [38]:
# find out details about some tensor
print(f"Some tensor: {some_tensor}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Some tensor: tensor([[0.0630, 0.7411, 0.7126, 0.6422],
        [0.7618, 0.5242, 0.3894, 0.4468],
        [0.8812, 0.2579, 0.1792, 0.4272]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Mulitplication (element-wise)
* Divison
* Matrix multiplication

In [39]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural neworks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [44]:
# element wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [45]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [47]:
%%timeit
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

11.1 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
%%timeit
value = torch.matmul(tensor, tensor)

1.07 µs ± 5.63 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### One of the most common errors in deep learning: shape errors

In [49]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.7676, 0.4120],
        [0.5194, 0.7014]])

In [51]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [52]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3)).shape

torch.Size([3, 3])

In [53]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [54]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [55]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [56]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [57]:
tensor_B.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [58]:
tensor_A.shape, tensor_B.T.shape # inner dimensions are same now after transpose

(torch.Size([3, 2]), torch.Size([2, 3]))

In [59]:
# the matrix multiplication operation works when tensor_B trasposed
print(f"Original shapes: \ntensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"\nNew shapes: \ntensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"\nMultiplication: \n{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"\nOutput:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: \n{output.shape}")

Original shapes: 
tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: 
tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])

Multiplication: 
torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: 
torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [91]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [92]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [93]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [102]:
x.dtype

torch.int64

In [94]:
# find the mean - note: the torch.mean() function requires a tensor of not int or long, it should be of type float
torch.mean(x, dtype=torch.float16), x.mean(dtype=torch.float16)

(tensor(46., dtype=torch.float16), tensor(46., dtype=torch.float16))

In [95]:
torch.mean(x.type(torch.float16)), x.type(torch.float16).mean()

(tensor(46., dtype=torch.float16), tensor(46., dtype=torch.float16))

In [96]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min max max

In [97]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [98]:
# fint the position in tensor that has the minimum value with argmin() -> returns index postiion of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [99]:
x[0]

tensor(1)

In [100]:
# finf the positions in tensor that has the maximum value with argmax() -> returns index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

In [101]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* `Reshaping` - reshapes an input tensor to a defined shape
* `View` - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* `Stacking` - combine multiple tensors on top of each other (vstack) or side by size (hstack)
* `Squeeze` - removes all `1` dimension from a tensor
* `Unsqueeze` - add a `1` dimension to a target tensor
* `Permute` - return a view of the input with dimension permnuted (swapped) in a certain way

In [123]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [124]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [125]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [126]:
# changing z changes x (because a view of a tensor share the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [129]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [136]:
# torch.squeeze() -  removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [137]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [138]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape # shape has changed after squeeze method

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [141]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add extra dimension from x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [162]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))
print(f"Previous shape: {x_original.shape}") # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
# NOTE: x_permute will share the same memory as x_original as it is a view
x_permute = torch.permute(x_original, (2, 0, 1)) # shifts axis 0->1, 1->2, 2->0
print(f"\nNew shape: {x_permute.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])

New shape: torch.Size([3, 224, 224])


In [163]:
x_original, x_original.shape

(tensor([[[0.1113, 0.7085, 0.0604],
          [0.3850, 0.0044, 0.0766],
          [0.3877, 0.4391, 0.4967],
          ...,
          [0.7203, 0.4048, 0.8883],
          [0.8754, 0.4328, 0.4444],
          [0.0163, 0.2051, 0.2824]],
 
         [[0.2473, 0.8269, 0.3869],
          [0.6157, 0.6740, 0.1761],
          [0.7739, 0.2015, 0.1881],
          ...,
          [0.6924, 0.3078, 0.6615],
          [0.0930, 0.2131, 0.4531],
          [0.7866, 0.9068, 0.6311]],
 
         [[0.8223, 0.9579, 0.1969],
          [0.6449, 0.7577, 0.2109],
          [0.0540, 0.7646, 0.1612],
          ...,
          [0.9069, 0.5148, 0.0240],
          [0.7876, 0.4951, 0.8193],
          [0.5989, 0.4003, 0.9363]],
 
         ...,
 
         [[0.7291, 0.0476, 0.6634],
          [0.8687, 0.1385, 0.5333],
          [0.4526, 0.8966, 0.7137],
          ...,
          [0.1156, 0.9080, 0.4205],
          [0.3363, 0.6038, 0.4307],
          [0.6465, 0.7492, 0.7306]],
 
         [[0.2073, 0.1919, 0.1844],
          [0

In [164]:
x_permute = torch.permute(x_original, (2, 0, 1))
x_permute, x_permute.shape

(tensor([[[0.1113, 0.3850, 0.3877,  ..., 0.7203, 0.8754, 0.0163],
          [0.2473, 0.6157, 0.7739,  ..., 0.6924, 0.0930, 0.7866],
          [0.8223, 0.6449, 0.0540,  ..., 0.9069, 0.7876, 0.5989],
          ...,
          [0.7291, 0.8687, 0.4526,  ..., 0.1156, 0.3363, 0.6465],
          [0.2073, 0.7222, 0.1121,  ..., 0.8922, 0.1495, 0.7349],
          [0.9140, 0.0108, 0.9337,  ..., 0.8790, 0.5157, 0.5921]],
 
         [[0.7085, 0.0044, 0.4391,  ..., 0.4048, 0.4328, 0.2051],
          [0.8269, 0.6740, 0.2015,  ..., 0.3078, 0.2131, 0.9068],
          [0.9579, 0.7577, 0.7646,  ..., 0.5148, 0.4951, 0.4003],
          ...,
          [0.0476, 0.1385, 0.8966,  ..., 0.9080, 0.6038, 0.7492],
          [0.1919, 0.8167, 0.4708,  ..., 0.1636, 0.1495, 0.9381],
          [0.7658, 0.1908, 0.3126,  ..., 0.7391, 0.8159, 0.3927]],
 
         [[0.0604, 0.0766, 0.4967,  ..., 0.8883, 0.4444, 0.2824],
          [0.3869, 0.1761, 0.1881,  ..., 0.6615, 0.4531, 0.6311],
          [0.1969, 0.2109, 0.1612,  ...,

In [165]:
x_original[0, 0, 0], x_permute[0, 0, 0]

(tensor(0.1113), tensor(0.1113))

In [169]:
# changing the value in the x_original changes the value of x_permute as well because they are sharing the same memory
x_original[0, 0, 0] = 123

In [168]:
x_original[0, 0, 0], x_permute[0, 0, 0]

(tensor(123.), tensor(123.))