### To check which gpu we are using if any available


In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


# 00. Pytorch Fundamentals


In [2]:
import torch
print(torch.__version__)

1.13.1


In [3]:
device = torch.device("mps")
device

device(type='mps')

## Introduction to Tensors

### Creating tensors


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# scalar dimention
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

7

In [7]:
scalar.shape

torch.Size([])

In [8]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
# vector dimention
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
# MATRIX dimension
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
# TENSOR dimension
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [19]:
# Create random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2778, 0.4706, 0.5126, 0.5648],
        [0.1845, 0.5872, 0.5629, 0.4988],
        [0.2898, 0.0897, 0.0952, 0.0902]])

In [20]:
# shape of the random tensor
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 244, 244))  # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zero and Ones


In [22]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [27]:
# use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [31]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32, float16, etc)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
# convert 32 bit tensor to the float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
# this is one of the pytorch caveats, 
# we might thing this will through an error but instead it works fine and will return the multiplication of float32 type
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information fromn tensors (tensor attributes)

1. Tensors not right datatype -  to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape` or `tensor.size()`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [37]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1929, 0.4722, 0.8622, 0.5905],
        [0.4153, 0.9255, 0.4387, 0.9300],
        [0.3282, 0.0580, 0.5820, 0.4984]])

In [38]:
# find out details about some tensor
print(f"Some tensor: {some_tensor}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Some tensor: tensor([[0.1929, 0.4722, 0.8622, 0.5905],
        [0.4153, 0.9255, 0.4387, 0.9300],
        [0.3282, 0.0580, 0.5820, 0.4984]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Mulitplication (element-wise)
* Divison
* Matrix multiplication

In [39]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural neworks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [44]:
# element wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [45]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [47]:
%%timeit
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

8.25 µs ± 23.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
%%timeit
value = torch.matmul(tensor, tensor)

729 ns ± 2.07 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### One of the most common errors in deep learning: shape errors

In [49]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6842, 0.6802],
        [0.6176, 0.7528]])

In [51]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [52]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3)).shape

torch.Size([3, 3])

In [53]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [54]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [55]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [56]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [57]:
tensor_B.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [58]:
tensor_A.shape, tensor_B.T.shape # inner dimensions are same now after transpose

(torch.Size([3, 2]), torch.Size([2, 3]))

In [59]:
# the matrix multiplication operation works when tensor_B trasposed
print(f"Original shapes: \ntensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"\nNew shapes: \ntensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"\nMultiplication: \n{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"\nOutput:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: \n{output.shape}")

Original shapes: 
tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: 
tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])

Multiplication: 
torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: 
torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [60]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [61]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [62]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [63]:
x.dtype

torch.int64

In [64]:
# find the mean - note: the torch.mean() function requires a tensor of not int or long, it should be of type float
torch.mean(x, dtype=torch.float16), x.mean(dtype=torch.float16)

(tensor(46., dtype=torch.float16), tensor(46., dtype=torch.float16))

In [65]:
torch.mean(x.type(torch.float16)), x.type(torch.float16).mean()

(tensor(46., dtype=torch.float16), tensor(46., dtype=torch.float16))

In [66]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min max max

In [67]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [68]:
# fint the position in tensor that has the minimum value with argmin() -> returns index postiion of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [69]:
x[0]

tensor(1)

In [70]:
# finf the positions in tensor that has the maximum value with argmax() -> returns index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

In [71]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* `Reshaping` - reshapes an input tensor to a defined shape
* `View` - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* `Stacking` - combine multiple tensors on top of each other (vstack) or side by size (hstack)
* `Squeeze` - removes all `1` dimension from a tensor
* `Unsqueeze` - add a `1` dimension to a target tensor
* `Permute` - return a view of the input with dimension permnuted (swapped) in a certain way

In [72]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [73]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [74]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
# changing z changes x (because a view of a tensor share the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [76]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
# torch.squeeze() -  removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [78]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape # shape has changed after squeeze method

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [80]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add extra dimension from x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [81]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))
print(f"Previous shape: {x_original.shape}") # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
# NOTE: x_permute will share the same memory as x_original as it is a view
x_permute = torch.permute(x_original, (2, 0, 1)) # shifts axis 0->1, 1->2, 2->0
print(f"\nNew shape: {x_permute.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])

New shape: torch.Size([3, 224, 224])


In [82]:
x_original, x_original.shape

(tensor([[[6.3453e-01, 1.5644e-01, 1.4362e-01],
          [1.8532e-02, 6.5833e-01, 1.6666e-01],
          [2.5359e-01, 1.1616e-01, 5.5256e-01],
          ...,
          [6.9072e-01, 1.3948e-01, 9.4538e-01],
          [1.8698e-01, 9.9232e-01, 8.1875e-01],
          [5.4907e-01, 9.1732e-04, 8.3150e-01]],
 
         [[2.3128e-01, 8.0283e-01, 6.7422e-01],
          [3.3990e-01, 8.4356e-02, 1.4944e-01],
          [8.3446e-01, 8.8648e-01, 7.1013e-01],
          ...,
          [4.3362e-01, 9.9125e-01, 8.4821e-01],
          [3.3703e-01, 7.4034e-01, 9.1330e-01],
          [8.3081e-01, 3.4691e-01, 9.6012e-02]],
 
         [[5.5177e-01, 6.1258e-01, 9.5537e-01],
          [4.6966e-01, 5.4147e-01, 3.8054e-02],
          [8.7517e-01, 3.9147e-01, 7.3555e-01],
          ...,
          [5.9975e-01, 4.6702e-01, 3.8200e-01],
          [6.8764e-01, 4.7828e-01, 2.5951e-01],
          [9.3668e-01, 4.1610e-02, 2.5253e-01]],
 
         ...,
 
         [[6.1275e-01, 4.2883e-01, 6.0271e-01],
          [5.1884e

In [83]:
x_permute = torch.permute(x_original, (2, 0, 1))
x_permute, x_permute.shape

(tensor([[[6.3453e-01, 1.8532e-02, 2.5359e-01,  ..., 6.9072e-01,
           1.8698e-01, 5.4907e-01],
          [2.3128e-01, 3.3990e-01, 8.3446e-01,  ..., 4.3362e-01,
           3.3703e-01, 8.3081e-01],
          [5.5177e-01, 4.6966e-01, 8.7517e-01,  ..., 5.9975e-01,
           6.8764e-01, 9.3668e-01],
          ...,
          [6.1275e-01, 5.1884e-01, 1.2094e-01,  ..., 2.3257e-01,
           6.3496e-01, 6.0502e-01],
          [3.4580e-01, 7.2401e-01, 4.3892e-01,  ..., 5.3091e-01,
           8.7605e-01, 2.3250e-01],
          [9.1961e-01, 9.0840e-01, 9.4421e-01,  ..., 5.7416e-01,
           4.7794e-01, 4.6936e-01]],
 
         [[1.5644e-01, 6.5833e-01, 1.1616e-01,  ..., 1.3948e-01,
           9.9232e-01, 9.1732e-04],
          [8.0283e-01, 8.4356e-02, 8.8648e-01,  ..., 9.9125e-01,
           7.4034e-01, 3.4691e-01],
          [6.1258e-01, 5.4147e-01, 3.9147e-01,  ..., 4.6702e-01,
           4.7828e-01, 4.1610e-02],
          ...,
          [4.2883e-01, 4.2911e-01, 2.0540e-02,  ..., 8.731

In [84]:
x_original[0, 0, 0], x_permute[0, 0, 0]

(tensor(0.6345), tensor(0.6345))

In [85]:
# changing the value in the x_original changes the value of x_permute as well because they are sharing the same memory
x_original[0, 0, 0] = 123

In [86]:
x_original[0, 0, 0], x_permute[0, 0, 0]

(tensor(123.), tensor(123.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [87]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [88]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [89]:
# lets index on the middle bracket (dim=1)
x[0][0] # or x[0, 0]

tensor([1, 2, 3])

In [90]:
# lets index of the most inner bracket (last dimension)
x[0][0][0] # or x[0, 0, 0]

tensor(1)

In [91]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [92]:
# get all values of 0th and 1th dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [93]:
# get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [94]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [95]:
# get index on x to return 9
x[:, 2, 2], x[0, 2, 2]

(tensor([9]), tensor(9))

In [96]:
# get index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it

* NumPy -> PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [97]:
# numpy array to tensor
import torch
import numpy as np

numpy_array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(numpy_array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise 
numpy_array, numpy_array.dtype, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

In [98]:
numpy_array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(numpy_array).type(torch.float32)
numpy_array, numpy_array.dtype, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [99]:
# change the value of numpy_array, what will this do to `tensor`?
numpy_array += 1
numpy_array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [100]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, tensor.dtype, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [101]:
# change the tensor, what happens to `numpy_tensor`?
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again....`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [102]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4578, 0.5514, 0.8858, 0.8908],
        [0.4450, 0.3360, 0.5061, 0.4071],
        [0.0101, 0.0209, 0.6017, 0.0010]])
tensor([[0.5623, 0.0545, 0.9143, 0.6500],
        [0.7762, 0.4515, 0.6863, 0.0372],
        [0.1428, 0.5978, 0.7627, 0.3771]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [103]:
# lets make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPU's (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behing the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options tp upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation

### 2. Check for GPU access with PyTorch

In [104]:
# check for GPU access with PyTorch
import torch

In [105]:
# setup device agnostic code
if torch.cuda.is_available():
    device = "cuda" # NVIDIA GPU
elif torch.backends.mps.is_available():
    device = "mps" # Apple GPU
else:
    device = "cpu" # Defaults to CPU if NVIDIA GPU/Apple GPU aren't available

print(f"Using device: {device}")

Using device: mps


In [106]:
# count number of devices - for NVIDEA
# torch.cuda.device_count()

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [107]:
# creata a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [108]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

### 4. Moving tensors back to the CPU

In [109]:
# if tensor in on GPU, can't transfor it ot NumPy
tensor_on_gpu.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [110]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [111]:
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')